language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install black
  - pip install flake8
# command to run tests
script:
  - black . --check
  - flake8 --config=pyproject.toml
